### ISSUE TITLE
Div keeps scrolling indefinitely

### ISSUE THREAD

**Issue by guns2410** [TimeToKnow/emoji-panel#1]
When clicking on the Tab, the div keeps on scrolling indefinitely freezing the entire page.

![ezgif com-optimize](https://cloud.githubusercontent.com/assets/1809012/16504183/4628bdf0-3f34-11e6-933a-e4263867cbb8.gif)

**Comment by unimonkiez** [comment]
Wow sorry for not replying.. didn't see those issues, anyway this bug is already fixed!
