### ISSUE TITLE
Uncaught TypeError: Cannot call a class as a function

### ISSUE THREAD

**Issue by tvChan** [TimeToKnow/emoji-panel#2]
Hi, i installed the emoji-panel plugin in the npm and use it in the vue project.

And when i add the example like you say, that showed the error like the title, i wonder know what wrong!

Thank you

**Comment by unimonkiez** [comment]
You might have forgot the `new` keyword..
Currently the panel doesn't have anymore functions to it besides the constructor, but that might change!

**Comment by unimonkiez** [comment]
I guess you've managed 👍
